### ISSUE TITLE
InvalidPacketException when reading in API escaped mode if checksum byte is escaped

### ISSUE THREAD

**Issue by mikewadsten** [digidotcom/python-xbee#13]
After applying a fix for #11, I am now running into another error that crops up from time to time.

```
original: 7E 02 0B B0 34 2B 79 4D 00 00 27 7D 31 00 00 3A 45 5F 49 4E 2C 5A 09 2D 72 0C 71 60 37 6A 6A 28 3E 5B 49 3A 5F 38 32 51 66 49 7B 46 48 49 42 3E 64 5C 60 2B 5F 50 78 09 58 5D 6B 41 78 51 25 2D 4B 70 24 20 60 61 62 7B 54 6A 23 53 2C 75 51 6C 70 54 32 51 6B 37 46 7B 48 51 22 54 3D 6C 52 57 54 2B 4F 2B 2D 6C 4E 37 47 6C 51 33 4E 56 39 40 7A 3C 69 7C 39 41 79 4D 61 49 31 2A 75 50 64 3E 57 51 3B 7D 5D 48 59 55 62 0C 3A 36 33 75 79 57 50 3C 46 28 45 5E 25 5A 2A 2F 43 24 5B 3F 6E 33 6C 2B 7D 5D 6C 22 74 34 59 3B 47 72 44 66 46 3D 53 25 60 21 3A 32 60 0A 47 2A 72 77 53 0A 60 66 46 52 20 61 55 0A 4F 7B 79 47 4F 43 2C 3F 53 5D 6D 78 32 32 3C 38 75 47 65 54 3A 40 76 6B 30 30 35 61 44 20 5D 42 5B 0C 0B 57 68 6A 44 6C 37 50 62 54 2F 46 5E 43 6A 6E 5F 6C 31 20 34 3E 6D 59 3F 2A 63 7B 66 2C 22 63 42 68 56 6E 61 21 36 33 57 6D 66 2A 60 32 45 32 5C 2D 2B 5E 31 4B 73 44 09 39 3F 2D 0B 68 49 47 30 49 4F 2C 6B 67 0C 63 0A 49 42 4E 38 3F 6F 65 7D 5E 42 38 6C 29 53 34 5C 3C 78 6D 56 3A 45 3A 58 5D 3A 0A 0C 3F 5A 31 56 67 51 28 7D 5D 4B 2B 7D 5E 44 5B 44 7D 5E 35 42 36 09 60 78 20 54 32 27 72 7D 5E 3F 25 2D 51 6B 37 37 7C 3C 2D 0A 7A 4B 2C 6B 30 34 7C 4D 47 6D 26 53 77 78 25 2A 4F 4C 76 74 6B 23 67 30 69 38 2E 42 40 2A 35 3B 6D 62 53 34 6B 0C 2D 45 4D 3A 23 29 78 59 23 09 3B 76 49 22 38 3E 5F 7D 5D 55 62 36 45 3A 4B 59 64 2D 61 4E 72 76 30 43 5D 76 46 34 46 4F 7B 59 30 54 7C 50 3E 48 31 72 2A 3F 55 6B 28 53 4B 6F 67 39 7D 5E 24 3B 34 7C 2F 25 77 6B 64 64 50 50 63 50 5C 75 46 75 2B 7C 2B 34 40 6E 35 2F 4A 6C 45 28 21 4D 48 62 75 21 62 72 2B 26 5D 09 46 5F 34 30 39 58 43 6F 3F 0C 67 31 73 5F 70 75 49 49 49 7D
escaped: 7E 02 0B B0 34 2B 79 4D 00 00 27 11 00 00 3A 45 5F 49 4E 2C 5A 09 2D 72 0C 71 60 37 6A 6A 28 3E 5B 49 3A 5F 38 32 51 66 49 7B 46 48 49 42 3E 64 5C 60 2B 5F 50 78 09 58 5D 6B 41 78 51 25 2D 4B 70 24 20 60 61 62 7B 54 6A 23 53 2C 75 51 6C 70 54 32 51 6B 37 46 7B 48 51 22 54 3D 6C 52 57 54 2B 4F 2B 2D 6C 4E 37 47 6C 51 33 4E 56 39 40 7A 3C 69 7C 39 41 79 4D 61 49 31 2A 75 50 64 3E 57 51 3B 7D 48 59 55 62 0C 3A 36 33 75 79 57 50 3C 46 28 45 5E 25 5A 2A 2F 43 24 5B 3F 6E 33 6C 2B 7D 6C 22 74 34 59 3B 47 72 44 66 46 3D 53 25 60 21 3A 32 60 0A 47 2A 72 77 53 0A 60 66 46 52 20 61 55 0A 4F 7B 79 47 4F 43 2C 3F 53 5D 6D 78 32 32 3C 38 75 47 65 54 3A 40 76 6B 30 30 35 61 44 20 5D 42 5B 0C 0B 57 68 6A 44 6C 37 50 62 54 2F 46 5E 43 6A 6E 5F 6C 31 20 34 3E 6D 59 3F 2A 63 7B 66 2C 22 63 42 68 56 6E 61 21 36 33 57 6D 66 2A 60 32 45 32 5C 2D 2B 5E 31 4B 73 44 09 39 3F 2D 0B 68 49 47 30 49 4F 2C 6B 67 0C 63 0A 49 42 4E 38 3F 6F 65 7E 42 38 6C 29 53 34 5C 3C 78 6D 56 3A 45 3A 58 5D 3A 0A 0C 3F 5A 31 56 67 51 28 7D 4B 2B 7E 44 5B 44 7E 35 42 36 09 60 78 20 54 32 27 72 7E 3F 25 2D 51 6B 37 37 7C 3C 2D 0A 7A 4B 2C 6B 30 34 7C 4D 47 6D 26 53 77 78 25 2A 4F 4C 76 74 6B 23 67 30 69 38 2E 42 40 2A 35 3B 6D 62 53 34 6B 0C 2D 45 4D 3A 23 29 78 59 23 09 3B 76 49 22 38 3E 5F 7D 55 62 36 45 3A 4B 59 64 2D 61 4E 72 76 30 43 5D 76 46 34 46 4F 7B 59 30 54 7C 50 3E 48 31 72 2A 3F 55 6B 28 53 4B 6F 67 39 7E 24 3B 34 7C 2F 25 77 6B 64 64 50 50 63 50 5C 75 46 75 2B 7C 2B 34 40 6E 35 2F 4A 6C 45 28 21 4D 48 62 75 21 62 72 2B 26 5D 09 46 5F 34 30 39 58 43 6F 3F 0C 67 31 73 5F 70 75 49 49 49
2018-01-05 18:02:06,754 digi.xbee.reader: ERROR: The real length of this frame is distinct than the specified by length field (bytes 2 and 3)
Traceback (most recent call last):
  File "/home/mike/.envs/env/src/digi-xbee/digi/xbee/reader.py", line 308, in run
    read_packet = factory.build_frame(raw_packet, self.__xbee_device.operating_mode)
  File "/home/mike/.envs/env/src/digi-xbee/digi/xbee/packets/factory.py", line 181, in build_frame
    return RXIPv4Packet.create_packet(packet_bytearray, operating_mode)
  File "/home/mike/.envs/env/src/digi-xbee/digi/xbee/packets/network.py", line 96, in create_packet
    XBeeAPIPacket._check_api_packet(raw, min_length=RXIPv4Packet.__MIN_PACKET_LENGTH)
  File "/home/mike/.envs/env/src/digi-xbee/digi/xbee/packets/base.py", line 397, in _check_api_packet
    raise InvalidPacketException("The real length of this frame is distinct than the specified by length "
digi.xbee.exception.InvalidPacketException: The real length of this frame is distinct than the specified by length field (bytes 2 and 3)
```

The first two lines are from print calls that I have added.

By copying the 'original' frame data into XCTU's frame interpreter, I can see that I'm missing a 0x5D (escaped `0x7D`) checksum byte at the end.

Perhaps the library is incorrectly calculating/accounting for escaped mode when reading in the API frame? According to the note [here](https://www.digi.com/resources/documentation/Digidocs/90001942-13/concepts/c_api_escaped_operating_mode.htm?TocPath=XBee%20API%20mode%7COperating%20mode%20configuration%7C_____1),

> In API 2 mode, the length field does not include any escape character in the frame and the checksum is calculated with non-escaped data.

I haven't captured my serial traffic using a Saleae device or something like that (perhaps I should), but I don't think I'm losing any traffic.

**Comment by mikewadsten** [comment]
Okay, it looks like `__try_read_packet` in `PacketListener` (`digi/xbee/reader.py`) doesn't expect the checksum byte itself to be escaped:

```python
...
            for _ in range(0, length):
                read_byte = self.__serial_port.read_byte()
                xbee_packet.append(read_byte)
                # Read escaped bytes in API escaped mode.
                if operating_mode == OperatingMode.ESCAPED_API_MODE and read_byte == XBeePacket.ESCAPE_BYTE:
                    xbee_packet.append(self.__serial_port.read_byte())
            # Add packet checksum.
            xbee_packet.append(self.__serial_port.read_byte())
            return xbee_packet
```
