### ISSUE TITLE
Not able to install through PIP

### ISSUE THREAD

**Issue by jyotirajsharma** [digidotcom/python-xbee#17]
Hi,
I am NOT able to install via PIP. pip install digi-xbee gives following error.
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/basecomma                  nd.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/commands/                  install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/pip-9.0.1-py2.7.egg/pip/req/req_s                  et.py", line 380, in prepare_files

**Comment by rubenmoral** [comment]
Hi @jyotirajsharma,

It seems that you are using Python 2.7. The library is only compatible with Python 3.

Regards.
