### ISSUE TITLE
serial.serialutil.SerialException: read failed: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by mjjunemann** [digidotcom/python-xbee#23]
Hi, I'm trying to use a very simple code 

```python
PORT = "COM3"
BAUD_RATE = 9600

DATA_TO_SEND = "Hello XBee!"
REMOTE_NODE_ID = "N1"

def main():
    device = XBeeDevice(PORT, BAUD_RATE)
    device.close()

    try:
        device.open()
        print("Connection Open")
        # Obtain the remote XBee device from the XBee network.
        device.close()
        print("Connection Closed")
   except Exception as err:
       print(err)
```

and i get this error:

```bash
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/matiasjunemann/Documents/Repositories/inti-tech/penv/lib/python3.6/site-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:
```

Basically I traced the error that the serial port it's getting closed twice on digi.xbee.device.py line 1285 and in digi.xbee.reader.py in line 327, when the reader its stop raises an exception and tries to close the serial port again. 

You can see it from the logs off the library, if you comment line 1285 closing works fine.

```bash
2018-01-24 16:43:02,794 - digi.xbee.devices - INFO - /dev/tty.usbserial-DN02YVHY port opened
2018-01-24 16:43:02,794 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 01 41 50 65
2018-01-24 16:43:02,818 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 06 88 01 41 50 00 01 E4
2018-01-24 16:43:02,818 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 02 48 56 57
2018-01-24 16:43:02,851 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 07 88 02 48 56 00 2E 48 61
2018-01-24 16:43:02,852 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 03 56 52 4C
2018-01-24 16:43:02,882 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 07 88 03 56 52 00 40 59 33
2018-01-24 16:43:02,883 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 04 53 48 58
2018-01-24 16:43:02,914 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 09 88 04 53 48 00 00 13 A2 00 23
2018-01-24 16:43:02,915 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 05 53 4C 53
2018-01-24 16:43:02,946 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 09 88 05 53 4C 00 41 5B 8C 17 94
2018-01-24 16:43:02,948 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 06 4E 49 5A
2018-01-24 16:43:02,978 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 07 88 06 4E 49 00 43 31 66
2018-01-24 16:43:02,979 - digi.xbee.devices - DEBUG - /dev/tty.usbserial-DN02YVHYSENT        OperatingMode.API_MODE7E 00 04 08 07 4D 59 4A
2018-01-24 16:43:03,009 - digi.xbee.reader - DEBUG - /dev/tty.usbserial-DN02YVHYRECEIVED    OperatingMode.API_MODE7E 00 07 88 07 4D 59 00 00 00 CA
1)
2018-01-24 16:43:03,116 - digi.xbee.devices - INFO - /dev/tty.usbserial-DN02YVHY port closed
Done
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/matiasjunemann/Documents/Repositories/inti-tech/penv/lib/python3.6/site-packages/serial/serialposix.py", line 483, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
OSError: [Errno 9] Bad file descriptor

```

I don't know if is intended or i missing something.

**Comment by rubenmoral** [comment]
Hi @mjjunemann,

We have fixed the issue (see commit 02febb6d0be7d0f48db252f2a124ff1f120e69d7), it will be included in the next release. In the meantime, you can download the source code from the `master` branch and install the library from there (see instructions at https://github.com/digidotcom/python-xbee/blob/master/README.rst#install-from-source).

Sorry for the inconvenience.

Best regards.
