### ISSUE TITLE
RE: BeagleBone Black, XBee S1, and THT Grove Adapter Board/Seth

### ISSUE THREAD

**Issue by silver2row** [digidotcom/python-xbee#43]
Hello,

I am using a BeagleBone Black Wireless via their Linux Distro w/ the THT dev. board from Digi. My wireless XBee is attached to the THT/Grove dev. board.

The dev. board and XBee is attached to the BeagleBone Black Wireless via the USB port on the BBBW located at ttyUSB0. That is the number 0 and not the letter O.

I found your software from 2017 at https://github.com/digidotcom/python-xbee/blob/master/examples/io/LocalDIOSample/LocalDIOSample.py.

So, I thought I could, since the OS is Debian (a Linux Distro), use ttyUSB0 instead of a com7 port for this particular attachment.

Now...

I am getting an error:

    Traceback (most recent call last):
      File "xBee.py", line 10, in <module>
        IO_LINE_IN = IOLine.DIO0_DO0
      File "/usr/lib/python3.5/enum.py", line 274, in __getattr__
        raise AttributeError(name) from None
    AttributeError: DIO0_DO0

line 10 reads: 

     IO_LINE_IN = IOLine.DIO0_DO0   

So...

I thought I had the connection incorrect or not at all ready for reading my receiver module that is located on a breadboard that would light up a LED.

This idea has already been accomplished and the LED lit up w/ my wiring and XCTU config. 

If you know why I am receiving the DIO0_DO0 error, please reply. I sure could use some ideas. If this does not have to do w/ your library or software, please let me know, too.

Seth

P.S. If you need any other info. from me, please contact me.

**Comment by silver2row** [comment]
Hello Again,

I tried to set up the ttyUSB0 device w/out success. I am going to try to set up the communication via Header Pins on the BBBW instead now.

Looking into the whole issue, I have found it may be easier to use the hardware of leads instead of relying on the USB device to just accept my THT/XBee as a plug and play device (even though, I think it does).

Seth

P.S. I will update you soon. If you have any ideas, please contact me.

**Comment by silver2row** [comment]
Hello,

Thank you. I will look up those items you have described.

Seth
